<?php
/**
 * CompanyDeveloperApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Company Developers API
 *
 * Associate developers with a company.  The company developer creates apps on behalf of the company. Any apps created by a company developer are associated with the company and known as \"company apps.\"  A developer must exist before you can associate them with a company.  When you add a developer to a company, you specify the developer's email and assign the developer a role. Company developer roles are enforced by the client app that you build using the API, not by Apigee. Therefore, when you retrieve a list of company apps on behalf of a developer, it is your code that checks the developer's role and displays the capabilities appropriate for that role. You typically create an admin role to allow a company developer to add other developers, delete company apps, and so on. Company developers are mapped to developers in your organization using the developer email as a key. The mapping associates the developer with the company and adds a role. The company developer entity simply stores an email address and a role while the organization developer entity that it maps to can have a wide variety of attributes defined.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * CompanyDeveloperApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompanyDeveloperApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addUpdateCompanyDevelopers
     *
     * Add or update company developers
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  \OpenAPI\Client\Model\CompanyDevelopers $company_developers Add or update a company developer. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\CompanyDevelopers
     */
    public function addUpdateCompanyDevelopers($org_name, $company_name, $company_developers = null)
    {
        list($response) = $this->addUpdateCompanyDevelopersWithHttpInfo($org_name, $company_name, $company_developers);
        return $response;
    }

    /**
     * Operation addUpdateCompanyDevelopersWithHttpInfo
     *
     * Add or update company developers
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  \OpenAPI\Client\Model\CompanyDevelopers $company_developers Add or update a company developer. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\CompanyDevelopers, HTTP status code, HTTP response headers (array of strings)
     */
    public function addUpdateCompanyDevelopersWithHttpInfo($org_name, $company_name, $company_developers = null)
    {
        $request = $this->addUpdateCompanyDevelopersRequest($org_name, $company_name, $company_developers);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\CompanyDevelopers' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\CompanyDevelopers', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\CompanyDevelopers';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CompanyDevelopers',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation addUpdateCompanyDevelopersAsync
     *
     * Add or update company developers
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  \OpenAPI\Client\Model\CompanyDevelopers $company_developers Add or update a company developer. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addUpdateCompanyDevelopersAsync($org_name, $company_name, $company_developers = null)
    {
        return $this->addUpdateCompanyDevelopersAsyncWithHttpInfo($org_name, $company_name, $company_developers)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addUpdateCompanyDevelopersAsyncWithHttpInfo
     *
     * Add or update company developers
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  \OpenAPI\Client\Model\CompanyDevelopers $company_developers Add or update a company developer. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addUpdateCompanyDevelopersAsyncWithHttpInfo($org_name, $company_name, $company_developers = null)
    {
        $returnType = '\OpenAPI\Client\Model\CompanyDevelopers';
        $request = $this->addUpdateCompanyDevelopersRequest($org_name, $company_name, $company_developers);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addUpdateCompanyDevelopers'
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  \OpenAPI\Client\Model\CompanyDevelopers $company_developers Add or update a company developer. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addUpdateCompanyDevelopersRequest($org_name, $company_name, $company_developers = null)
    {
        // verify the required parameter 'org_name' is set
        if ($org_name === null || (is_array($org_name) && count($org_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_name when calling addUpdateCompanyDevelopers'
            );
        }
        // verify the required parameter 'company_name' is set
        if ($company_name === null || (is_array($company_name) && count($company_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_name when calling addUpdateCompanyDevelopers'
            );
        }

        $resourcePath = '/organizations/{org_name}/companies/{company_name}/developers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($org_name !== null) {
            $resourcePath = str_replace(
                '{' . 'org_name' . '}',
                ObjectSerializer::toPathValue($org_name),
                $resourcePath
            );
        }
        // path params
        if ($company_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company_name' . '}',
                ObjectSerializer::toPathValue($company_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($company_developers)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($company_developers));
            } else {
                $httpBody = $company_developers;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listDevelopersCompany
     *
     * List developers in company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\CompanyDevelopers
     */
    public function listDevelopersCompany($org_name, $company_name)
    {
        list($response) = $this->listDevelopersCompanyWithHttpInfo($org_name, $company_name);
        return $response;
    }

    /**
     * Operation listDevelopersCompanyWithHttpInfo
     *
     * List developers in company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\CompanyDevelopers, HTTP status code, HTTP response headers (array of strings)
     */
    public function listDevelopersCompanyWithHttpInfo($org_name, $company_name)
    {
        $request = $this->listDevelopersCompanyRequest($org_name, $company_name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\CompanyDevelopers' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\CompanyDevelopers', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\CompanyDevelopers';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CompanyDevelopers',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listDevelopersCompanyAsync
     *
     * List developers in company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDevelopersCompanyAsync($org_name, $company_name)
    {
        return $this->listDevelopersCompanyAsyncWithHttpInfo($org_name, $company_name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listDevelopersCompanyAsyncWithHttpInfo
     *
     * List developers in company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDevelopersCompanyAsyncWithHttpInfo($org_name, $company_name)
    {
        $returnType = '\OpenAPI\Client\Model\CompanyDevelopers';
        $request = $this->listDevelopersCompanyRequest($org_name, $company_name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listDevelopersCompany'
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listDevelopersCompanyRequest($org_name, $company_name)
    {
        // verify the required parameter 'org_name' is set
        if ($org_name === null || (is_array($org_name) && count($org_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_name when calling listDevelopersCompany'
            );
        }
        // verify the required parameter 'company_name' is set
        if ($company_name === null || (is_array($company_name) && count($company_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_name when calling listDevelopersCompany'
            );
        }

        $resourcePath = '/organizations/{org_name}/companies/{company_name}/developers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($org_name !== null) {
            $resourcePath = str_replace(
                '{' . 'org_name' . '}',
                ObjectSerializer::toPathValue($org_name),
                $resourcePath
            );
        }
        // path params
        if ($company_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company_name' . '}',
                ObjectSerializer::toPathValue($company_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation removeDeveloperCompany
     *
     * Remove developer from company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  string $developer_email Email address of the developer. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function removeDeveloperCompany($org_name, $company_name, $developer_email)
    {
        $this->removeDeveloperCompanyWithHttpInfo($org_name, $company_name, $developer_email);
    }

    /**
     * Operation removeDeveloperCompanyWithHttpInfo
     *
     * Remove developer from company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  string $developer_email Email address of the developer. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeDeveloperCompanyWithHttpInfo($org_name, $company_name, $developer_email)
    {
        $request = $this->removeDeveloperCompanyRequest($org_name, $company_name, $developer_email);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation removeDeveloperCompanyAsync
     *
     * Remove developer from company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  string $developer_email Email address of the developer. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeDeveloperCompanyAsync($org_name, $company_name, $developer_email)
    {
        return $this->removeDeveloperCompanyAsyncWithHttpInfo($org_name, $company_name, $developer_email)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation removeDeveloperCompanyAsyncWithHttpInfo
     *
     * Remove developer from company
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  string $developer_email Email address of the developer. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeDeveloperCompanyAsyncWithHttpInfo($org_name, $company_name, $developer_email)
    {
        $returnType = '';
        $request = $this->removeDeveloperCompanyRequest($org_name, $company_name, $developer_email);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'removeDeveloperCompany'
     *
     * @param  string $org_name Organization name. (required)
     * @param  string $company_name Company name. (required)
     * @param  string $developer_email Email address of the developer. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function removeDeveloperCompanyRequest($org_name, $company_name, $developer_email)
    {
        // verify the required parameter 'org_name' is set
        if ($org_name === null || (is_array($org_name) && count($org_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_name when calling removeDeveloperCompany'
            );
        }
        // verify the required parameter 'company_name' is set
        if ($company_name === null || (is_array($company_name) && count($company_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_name when calling removeDeveloperCompany'
            );
        }
        // verify the required parameter 'developer_email' is set
        if ($developer_email === null || (is_array($developer_email) && count($developer_email) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $developer_email when calling removeDeveloperCompany'
            );
        }

        $resourcePath = '/organizations/{org_name}/companies/{company_name}/developers/{developer_email}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($org_name !== null) {
            $resourcePath = str_replace(
                '{' . 'org_name' . '}',
                ObjectSerializer::toPathValue($org_name),
                $resourcePath
            );
        }
        // path params
        if ($company_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company_name' . '}',
                ObjectSerializer::toPathValue($company_name),
                $resourcePath
            );
        }
        // path params
        if ($developer_email !== null) {
            $resourcePath = str_replace(
                '{' . 'developer_email' . '}',
                ObjectSerializer::toPathValue($developer_email),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
